/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./components/core/BaseIcon.vue')['default']
    BaseSelect: typeof import('./components/BaseSelect.vue')['default']
    Construction: typeof import('./components/Card/Construction.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    FederalProgram: typeof import('./components/Card/FederalProgram.vue')['default']
    FooterNav: typeof import('./components/FooterNav.vue')['default']
    Gosuslugi: typeof import('./components/Card/Gosuslugi.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    'Header copy': typeof import('./components/Header copy.vue')['default']
    IconCard: typeof import('./components/IconCard.vue')['default']
    Investments: typeof import('./components/Card/Investments.vue')['default']
    Item: typeof import('./components/map/item.vue')['default']
    LeftContent: typeof import('./components/LeftContent.vue')['default']
    Map: typeof import('./components/map/index.vue')['default']
    MapG: typeof import('./components/MapG.vue')['default']
    MapG2: typeof import('./components/MapG2.vue')['default']
    Marquee: typeof import('./components/Marquee.vue')['default']
    NavPanel: typeof import('./components/NavPanel.vue')['default']
    NavPanel2: typeof import('./components/NavPanel2.vue')['default']
    NavPanelCUR: typeof import('./components/NavPanelCUR.vue')['default']
    NavPanelCURBis: typeof import('./components/NavPanelCURBis.vue')['default']
    NavPanelRefPr: typeof import('./components/NavPanelRefPr.vue')['default']
    Provision: typeof import('./components/Card/Provision.vue')['default']
    Roads: typeof import('./components/Card/Roads.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./components/Card/Service.vue')['default']
    SocialSupport: typeof import('./components/Card/SocialSupport.vue')['default']
    SocioEconomic: typeof import('./components/Card/SocioEconomic.vue')['default']
    Transportation: typeof import('./components/Card/Transportation.vue')['default']
    Welfare: typeof import('./components/Card/Welfare.vue')['default']
  }
}
